### PR TITLE
Quiz finsight page

### PR DESCRIPTION
**Pull request by poojakelkar**
- Added Quiz-Finsight page

Live Link: https://ng-mini-website.netlify.app/quiz-finsight-page/index.html

### CODE REVIEW

**Review by sahiba0915 — COMMENTED** [review]
your code looks clean and good to merge

**Comment by poojakelkar** [comment]
Thanks @sahiba0915

**Review by HarshnaNHaswani — APPROVED** [review]
Looks good to me

**Comment by poojakelkar** [comment]
Thanks @HarshnaNHaswani

**Pull request merged**
