### PR TITLE
Correct answer

### PR DESCRIPTION
**Pull request by poojakelkar**
- Added Correct-Answer page in the mini website.

Live Link: https://ng-mini-website.netlify.app/correct-answer/index.html

### CODE REVIEW

**Review by sanjay-xdr — APPROVED** [review]
Looks good

**Comment by poojakelkar** [comment]
Thanks @sanjay-xdr

**Review by shrushti2000 — APPROVED** [review]
Overall everything looks good. Just a suggestion, you can display the score at the bottom.

**Comment by poojakelkar** [comment]
Yeah I have added it in result page Thank you @shrushti2000  for review

**Pull request merged**
